### ISSUE TITLE
뷰 엔드포인트 및 테스트 정의

### ISSUE THREAD

**Issue by daecheolsong** [daecheolsong/board-admin-project#8]
어드민 서비스에 필요한 뷰 엔드포인트 및 테스트 정의

## TODO
* [ ] 루트 페이지
* 관리 페이지
  * [ ] 댓글 관리 페이지
  * [ ] 게시글 관리 페이지
  * [ ] 회원 관리 페이지
  * [ ] 어드민 회원 페이지
